### ISSUE TITLE
Сверстать  элементы для списков 

### ISSUE THREAD

**Issue by d-fedorenko-dev** [d-kolesnikova/weather#2]
## Сделать отдельные layouts для представления горизонтального и вертикального списков. 

- [x] - Предусмотреть различные варианты иконок(загрузить в проект) 
- [x] - Проверить как растягиваются элементы
- [x] - Проверить как выглядит верстка основного экрана со вставленными элементами(поправить неточности)  Для этого можно использовать ```tools:listitem="@layout/имя" ``` внутри тега recycler view.

**Comment by d-fedorenko-dev** [comment]
![image](https://user-images.githubusercontent.com/19388782/127564642-f147687b-e653-4a29-875e-09dca231b42d.png)
![image](https://user-images.githubusercontent.com/19388782/127564715-a8fa12b4-3f57-40fd-aa81-c2a97cab70f7.png)

**Comment by d-kolesnikova** [comment]
#3
